name: "新条目补充"
description: "申请加入新的条目。"
title: "[New]: "
labels: ["★ 条目补充"]
body:
- type: textarea
  id: new_description
  attributes:
    label: "描述"
    description: "请尽可能详细地描述你想加入的条目。"
  validations:
    required: true
- type: textarea
  id: new_code
  attributes:
    label: "Markdown 代码"
    description: "如果可以，请使用代码块提供对应的 Markdown 代码。"
