name: pr 自动批准与标签

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write

jobs:
  manage-label-and-approve:
    runs-on: ubuntu-latest
    steps:
      - name: 添加标签
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.review.user.login == 'WForst-Breeze'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['⇵ 通过']
            })
      - name: 批准PR
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, '⇵ 通过')
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.ACTIONS }}
