name: 自动请求审查

on:
  pull_request:
    types: [opened, reopened]

jobs:
  request_review:
    runs-on: ubuntu-latest
    steps:
    - name: 请求WForst-Breeze的审查
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo, number } = context.issue;
          const reviewers = ['WForst-Breeze'];
          await github.pulls.createReviewRequest({ owner, repo, pull_number: number, reviewers });